version: "3"
services:
  redis:
    image: redis

  
  db: 
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redis

  vote:
    image: voting-app
    ports:
      - 5000:80

 
  worker:      
    image: worker-app

  
  result:
    image: result-app
    ports:
      - 5001:80 
